// <auto-generated />
namespace HS.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CPT));
        
        string IMigrationMetadata.Id
        {
            get { return "202109221241280_CPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
